### ISSUE TITLE
Race condition in scanned repository cleanup

### ISSUE THREAD

**Issue by Iwomichu** [Software-Engineering-Jagiellonian/django-celery-frege#91] opened 2023-03-24 12:21 UTC
It looks like there is a race condition when the crawl worker checks the temp folder and the other worker cleans it up.

```
[2023-03-23 19:50:46,932: ERROR/ForkPoolWorker-226] Task fregepoc.repositories.t
asks.crawl_repos_task[d37bcb15-67e5-4d3c-9294-eab6c80a3b7d] raised unexpected: F
ileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/app/fregepoc/repositories/tasks.py", line 140, in crawl_repos_task
    _check_download_folder_size()
  File "/app/fregepoc/repositories/tasks.py", line 79, in _check_download_folder_size
    files = list(
  File "/usr/local/lib/python3.10/pathlib.py", line 1034, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.10/pathlib.py", line 493, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/local/lib/python3.10/pathlib.py", line 440, in _select_from
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/frege/gollum-lib'
```

**Comment by fowczarek** [comment] 2023-04-29 15:21
Hello @Iwomichu, 
My suggestion for resolving this issue could be to use [select_for_update](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#select-for-update) in line where you fetching `RepositoryFile` in `analyze_file_task`. This should prevent file to be processed by multiple task in the same time.

**Comment by fowczarek** [comment] 2023-04-29 15:40
You also could improve this code by changing file processing logic to:
1. To `RepositoryFile` add bool field eg. "to_remove" with default value `False`
1. Task should fetch `RepositoryFile` from DB with `select_for_update`
2. Task should process file and save data to database(Do not forget to set `to_remove=True`)
3. Task shouldn't remove the file from disk.

Create a new task with the usage of [periodic task](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#crontab-schedules). Trigger this task eg. every 5 min. This task should remove only marked files from the drive with the use `RepositoryFile.objects.filter(to_remove=True)`.

**Comment by konradporeba** [comment] 2023-09-08 13:01
Actually problem was a little bit different and it's inside `path.glob()` function. 
![Screenshot from 2023-09-08 14-46-54](https://github.com/Software-Engineering-Jagiellonian/django-celery-frege/assets/34138284/a58227cd-47c9-4d0c-9290-5ecca9c57756)
In line 120 we are doing check if file exists before accessing it's size (because celery tasks might in the same time finish analysis and delete task between time file is added to the list and time of checking it's size) and it works ok but the problem is that while creating list of files using `files = list(path.glob("**/*"))` path.glob is doing similar for loop inside it and firstly it gets all files and directories in root folder so it can then iterate on them in depth to reveal sub directories. And problem was that inside `path.glob()` function in the time between all dirs in root folder were gathered and the time it was checked celery task deleted file and `path.glob()` didn't have the same kind of protection it seems as our code to check if file exists before doing anything with it. Long story short putting everything in `_check_download_folder_size()` function in to try except clauses like on the screen below fixed the problem and FREGE is continuously gathering metrics without any problems (at a time of writing the comment during 4 days of continuous work around 2500 repositories were analyzed)
![Screenshot from 2023-09-08 14-56-57](https://github.com/Software-Engineering-Jagiellonian/django-celery-frege/assets/34138284/beeba845-8dc2-406e-ad78-647013bcb7d0)

**Closed** 2023-09-08 13:06 UTC
Labels: bug
